# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
source 'https://github.com/CocoaPods/Specs.git'

#flutter_application_path = '../flutter_module'
#load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'OCStudyDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OCStudyDemo
  pod 'AFNetworking', '~> 3.0'
  pod 'SDWebImage', '~> 4.0.0'

#  install_all_flutter_pods(flutter_application_path)
  flutter_application_path = '../flutter_module'
  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)

  
  target 'OCStudyDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OCStudyDemoUITests' do
    # Pods for testing
  end

end

# 解决老项目在Xcode14.3上无法运行模拟器问题
#ld: file not found: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphonesimulator.a
#clang: error: linker command failed with exit code 1 (use -v to see invocation)
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end
