# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

#flutter_application_path = '../flutter_module'
#load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'OCStudyDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OCStudyDemo
  pod 'AFNetworking', '~> 3.0'
  pod 'SDWebImage', '~> 4.0.0'

#  install_all_flutter_pods(flutter_application_path)
  flutter_application_path = '../flutter_module'
  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)

  
  target 'OCStudyDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OCStudyDemoUITests' do
    # Pods for testing
  end

end
