# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'OCStudyDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OCStudyDemo
  pod 'AFNetworking', '~> 3.0'

  
  target 'OCStudyDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OCStudyDemoUITests' do
    # Pods for testing
  end

end
